import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import NextTopLoader from "nextjs-toploader";
import { EdgeStoreProvider } from "@/lib/edgestore";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Chatz: Meet, Chat, and Connect!",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <NextTopLoader />
          <Navbar />
          <main className="mt-16 min-h-screen">
            <EdgeStoreProvider>{children}</EdgeStoreProvider>
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
